### ISSUE TITLE
Support for gradient presets

### ISSUE THREAD

**Issue by Levdbas** [roots/palette-webpack-plugin#14]
* [x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
* [x] This request isn't a duplicate of an existing request
* [x] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

## Summary

Add the ability to fill the editor-gradient-presets in similar way as the color palette via this plugin.

## Motivation

Having to manage your brand colors in once place instead of 2 is great! I use it every single day in my new gutenberg era way of work. As there is now gradient support in a very easy way in custom blocks I would love to see this supported by the pallete-webpack-plugin.

## Additional context

Gradient presets also have three parts to be filled.

```php
add_theme_support(
      'editor-gradient-presets',
      [
         [
            'name'     => Red to transparent,
            'gradient' => 'linear-gradient(180deg,#263e45 0,rgba(38,62,69,.8) 10%,rgba(38,62,69,0)',
            'slug'     => 'red-to-transparent',
         ],
      ]
   );
```

So i think the output function almost can be the same but then outputs to a gradients.json? I'd love to hear what you think.

**Comment by Log1x** [comment]
I'm definitely for this idea and have thought about it. 

I mainly just don't know how we'd process this properly, specifically in Tailwind. What the user puts in the config doesn't give us much to play with gradient-wise given all the properties are set with [CSS Vars](https://github.com/tailwindlabs/tailwindcss/blob/b86bdbcd7ef8392db25d396eafb7e91932e1b990/src/plugins/gradientColorStops.js#L30-L31).

After that comes SASS Maps which we still need to figure out a way to ditch `sass-export` so we can get rid of this plugin annoyingly bringing in `node-sass`.

I'm open to brainstorming for sure, but right now I'm not sure if there's a steady approach.

**Comment by Levdbas** [comment]
I looked into the tailwind docs and I cannot find a smart way to incorporate this. Regarding sass-export. I am hoping that my PR https://github.com/plentycode/sass-export/pull/63 to at least update all the dependencies gets accepted. I even have a commit ready that ditches node-sass for dart sass. So hopefully at some point this gives us one less thing to worry about.

**Comment by Levdbas** [comment]
Stage one of my effort to get sass-export updated is completed. They just released an updated version with all the dependencies bumped: https://github.com/plentycode/sass-export/releases/tag/1.0.7

I just made a new PR for ditching node-sass in favor of dart sass. So hopefully I can get the momentum going over there. https://github.com/plentycode/sass-export/pull/64

**Comment by Levdbas** [comment]
V2 of sass-export is out now with dart-sass instead of node-sass: https://github.com/plentycode/sass-export/releases/tag/2.0.0
