### ISSUE TITLE
Feature Request: `theme.json` palette support

### ISSUE THREAD

**Issue by strarsis** [roots/palette-webpack-plugin#23]
### Terms

- [X] I have read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
- [X] This request is not a duplicate of an existing issue
- [X] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

### Summary

A theme `theme.json` is the new, best-practices standard for defining theme-specific settings (primarily used for the Gutenberg editor), including the palette.

#### Why are we doing this?
The `theme.json` can (and should be) used for declaring the theme palette.

#### What use cases does it support?
All new themes (mainly tailored to Gutenberg) that declare the theme palette in `theme.json`.

#### What is the expected outcome?
Less config duplication.
The usage of a standardized place for the theme palette.

#### Potential conflicts / foreseeable issues
When the option for adding/merging in more palettes besides from the `theme.json` is kept, 
there should be no conflicts or issues.

**Comment by retlehs** [comment]
https://github.com/roots/sage/pull/2999
https://roots.io/automatically-generating-theme-json-from-tailwind-config/
